project:
  type: website

website:
  title: "Leon Reteig"
  navbar:
    logo: icon.png
  page-footer:
    center: "Made by Leon Reteig, with [Quarto](https://quarto.org/) | [{{< iconify mdi github >}}](https://github.com/lcreteig/website)"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



